In [2]:
import numpy as np

In [3]:
test_ex = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_ex

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
test_ex[0][2]

3

In [5]:
test_ex[0, 2]

3

In [8]:
test_ex[0, 0] = 10
test_ex

array([[10,  2,  3],
       [ 4,  5,  6]])

In [9]:
test_ex[1, 2] = 5
test_ex[1, 2]

5

## slicing

In [10]:
test_ex = np.array([[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], int)
test_ex[:, 2:]

array([[5, 8],
       [5, 8],
       [5, 8],
       [5, 8]])

In [11]:
test_ex[:, 1:3].shape

(4, 2)

In [12]:
test_ex[1:2, :2]  # 해당 행렬은 어쨌든 2차원 어레이이므로 1차원의 값을 slicing해도 2차원 어레이로 반환

array([[1, 2]])

In [13]:
test_ex[1]  # 이럴 때에는 1차원으로 나옴 (1개의 인자로만 지정했음)

array([1, 2, 5, 8])

In [15]:
test_ex[1:2]  # 위의 코드와 같은 행을 출력하나, 2차원으로 나옴 (여러개를 지정해서 그럼)

array([[1, 2, 5, 8]])

In [16]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
a[:, -1]  # slicing이 아닌 인수로 지정하면, 1차원 어레이로 나온다...

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

## arange

In [18]:
list(range(0, 10, 3))

[0, 3, 6, 9]

In [19]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
np.arange(0, 10, 0.5)  # float point로 step 변화 가능

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [21]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## ones, zeros & empty

In [23]:
np.zeros(shape=10, dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [24]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones(10, dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [27]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.empty(10, np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [29]:
np.empty((10, 5))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        6.95272535e-310, 2.27270197e-322],
       [9.37078661e-312, 9.37078661e-312, 6.95272535e-310,
        6.95272536e-310, 6.95272542e-310],
       [6.95272535e-310, 6.95272536e-310, 6.95272535e-310,
        9.37078376e-312, 6.95272535e-310],
       [6.95272536e-310, 6.95272537e-310, 6.95272542e-310,
        9.37078660e-312, 6.95272542e-310],
       [6.95272542e-310, 6.95272536e-310, 6.95272535e-310,
        6.95272537e-310, 6.95272536e-310],
       [6.95272536e-310, 6.95272536e-310, 6.95272542e-310,
        6.95272536e-310, 9.37078660e-312],
       [6.95272542e-310, 9.37078660e-312, 9.37078661e-312,
        6.95272536e-310, 6.95272536e-310],
       [6.95272537e-310, 6.95272535e-310, 6.95272542e-310,
        9.37078661e-312, 6.95272536e-310],
       [6.95272536e-310, 9.37078661e-312, 6.95272535e-310,
        6.95272535e-310, 6.95272535e-310],
       [6.95272536e-310, 6.95272537e-310, 6.95272535e-310,
        6.95272535e-310

In [30]:
test_mat = np.arange(100).reshape(5, -1)
test_mat.shape

(5, 20)

In [31]:
np.zeros_like(test_mat, np.int8)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int8)

## eye, identity & digonal

In [32]:
np.identity(10, np.int8)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [35]:
np.eye(3, 5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(3, 5, k=2)  # k에 따라 시작 위치가 달라짐

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
mat = np.arange(12).reshape(3, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
np.diag(mat, k=2)  # 여기도 마찬가지로 k를 시작위치로 함

array([2, 7])

In [40]:
np.diag(mat, k=-1)  # 여기도 마찬가지로 k를 시작위치로 함

array([4, 9])

In [41]:
np.diag(mat, k=1)  # 여기도 마찬가지로 k를 시작위치로 함

array([ 1,  6, 11])

## random sampling - numpy.random

In [42]:
np.random.normal(0,1,10).reshape(2,5)

array([[-0.51422094,  1.36851731, -1.10065686, -1.2032458 ,  0.96576961],
       [ 0.16783137,  0.09111494, -0.28392347,  1.01269106, -0.02343072]])

In [43]:
np.random.exponential(scale=2, size=100)

array([0.95660778, 0.290303  , 2.60680878, 3.91058729, 0.12247774,
       4.2753567 , 3.72403775, 0.93024769, 0.68746146, 1.10072049,
       5.97588257, 0.0689448 , 0.77142699, 2.69733819, 2.01183593,
       5.21676115, 4.43899557, 2.8966017 , 1.00482723, 1.17868   ,
       2.00759032, 4.14627892, 0.33953716, 0.0902799 , 0.74069582,
       3.69017773, 2.89110218, 1.52587443, 0.55851768, 0.31031778,
       0.60171438, 3.56951166, 0.24720191, 0.74087969, 2.14948757,
       1.56179106, 1.18744025, 1.22310576, 1.51283303, 0.84141141,
       2.86127336, 3.02444432, 0.7012541 , 5.27981935, 2.50170153,
       0.42804473, 0.0494681 , 3.05796513, 1.35328128, 0.46254936,
       3.07877228, 0.14477728, 0.65537977, 0.37200349, 4.4919611 ,
       1.48252021, 1.41198001, 0.49282513, 3.1280631 , 7.19181737,
       1.11097902, 3.78836098, 0.3405722 , 2.26027333, 3.57284647,
       3.3454408 , 2.75700413, 3.61584078, 1.70401408, 1.025322  ,
       0.47541957, 0.64694806, 2.51681642, 1.31354735, 0.14156