In [1]:
import numpy as np

In [2]:
test_ex = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_ex

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
test_ex[0][2]

3

In [4]:
test_ex[0, 2]

3

In [5]:
test_ex[0, 0] = 10
test_ex

array([[10,  2,  3],
       [ 4,  5,  6]])

In [6]:
test_ex[1, 2] = 5
test_ex[1, 2]

5

## slicing

In [7]:
test_ex = np.array([[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], int)
test_ex[:, 2:]

array([[5, 8],
       [5, 8],
       [5, 8],
       [5, 8]])

In [8]:
test_ex[:, 1:3].shape

(4, 2)

In [9]:
test_ex[1:2, :2]  # 해당 행렬은 어쨌든 2차원 어레이이므로 1차원의 값을 slicing해도 2차원 어레이로 반환

array([[1, 2]])

In [10]:
test_ex[1]  # 이럴 때에는 1차원으로 나옴 (1개의 인자로만 지정했음)

array([1, 2, 5, 8])

In [11]:
test_ex[1:2]  # 위의 코드와 같은 행을 출력하나, 2차원으로 나옴 (여러개를 지정해서 그럼)

array([[1, 2, 5, 8]])

In [12]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
a[:, -1]  # slicing이 아닌 인수로 지정하면, 1차원 어레이로 나온다...

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

## arange

In [14]:
list(range(0, 10, 3))

[0, 3, 6, 9]

In [15]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
np.arange(0, 10, 0.5)  # float point로 step 변화 가능

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [17]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## ones, zeros & empty

In [18]:
np.zeros(shape=10, dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [19]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(10, dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [21]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.empty(10, np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [23]:
np.empty((10, 5))

array([[9.92912957e-312, 9.92882711e-312, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.45221679e-308,
        9.92882660e-312, 9.92882660e-312],
       [9.92920802e-312, 9.92920802e-312, 9.92922039e-312,
        6.95340875e-317, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000

In [24]:
test_mat = np.arange(100).reshape(5, -1)
test_mat.shape

(5, 20)

In [25]:
np.zeros_like(test_mat, np.int8)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int8)

## eye, identity & digonal

In [26]:
np.identity(10, np.int8)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [27]:
np.eye(3, 5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.eye(3, 5, k=2)  # k에 따라 시작 위치가 달라짐

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
mat = np.arange(12).reshape(3, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
np.diag(mat, k=2)  # 여기도 마찬가지로 k를 시작위치로 함

array([2, 7])

In [32]:
np.diag(mat, k=-1)  # 여기도 마찬가지로 k를 시작위치로 함

array([4, 9])

In [33]:
np.diag(mat, k=1)  # 여기도 마찬가지로 k를 시작위치로 함

array([ 1,  6, 11])

## random sampling - numpy.random

In [34]:
np.random.normal(0,1,10).reshape(2,5)

array([[-0.23797617, -0.26720817, -0.70944922, -0.20528087, -1.75042873],
       [-1.35956623,  0.91574892,  0.444606  , -0.25712243,  1.34574653]])

In [35]:
np.random.exponential(scale=2, size=100)

array([ 0.51045697,  0.70439737,  0.81617627,  4.83555116,  0.41325817,
        4.63397704,  1.29114835,  1.47136674,  0.81200446,  0.98517852,
        6.02038205,  0.64828722,  6.36438517,  1.57902015,  2.5164476 ,
        0.78971817,  3.64954646,  0.84212742,  0.30232615,  0.98675538,
        2.21009712,  0.9914962 ,  0.17209578,  1.75374184,  1.12008282,
        1.42636626,  3.04962678,  5.87126699,  0.08418252,  0.24811073,
        0.15732633,  0.679009  ,  0.42044425,  1.63081472,  3.10784415,
        1.10402091,  0.39442784,  6.81964331,  5.33996704,  3.09438596,
        3.78804873,  0.47349622,  3.83701512,  0.40617163,  1.89620058,
        0.24378213,  5.21793221,  2.15138539,  1.96426048,  3.64694496,
        0.3249749 ,  4.08257327,  8.51146759,  0.88769135,  8.69033758,
        7.6805056 ,  0.38873575,  0.28106798,  0.92228341,  1.40657219,
        3.87833199,  2.17972548,  4.03967854,  0.61550287,  0.2677294 ,
        1.01471754,  1.8938006 ,  3.28752508,  2.01748442,  4.32