In [1]:
import numpy as np

In [2]:
test_ex = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_ex

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
test_ex[0][2]

3

In [4]:
test_ex[0, 2]

3

In [5]:
test_ex[0, 0] = 10
test_ex

array([[10,  2,  3],
       [ 4,  5,  6]])

In [6]:
test_ex[1, 2] = 5
test_ex[1, 2]

5

## slicing

In [7]:
test_ex = np.array([[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], int)
test_ex[:, 2:]

array([[5, 8],
       [5, 8],
       [5, 8],
       [5, 8]])

In [8]:
test_ex[:, 1:3].shape

(4, 2)

In [9]:
test_ex[1:2, :2]  # 해당 행렬은 어쨌든 2차원 어레이이므로 1차원의 값을 slicing해도 2차원 어레이로 반환

array([[1, 2]])

In [10]:
test_ex[1]  # 이럴 때에는 1차원으로 나옴 (1개의 인자로만 지정했음)

array([1, 2, 5, 8])

In [11]:
test_ex[1:2]  # 위의 코드와 같은 행을 출력하나, 2차원으로 나옴 (여러개를 지정해서 그럼)

array([[1, 2, 5, 8]])

In [12]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
a[:, -1]  # slicing이 아닌 인수로 지정하면, 1차원 어레이로 나온다...

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])