# Numpy

In [2]:
import numpy as np

In [3]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]

In [4]:
a =np.array(a, int)
a

array([1, 2, 3, 4, 5])

In [5]:
test_array = np.array(["1", "4", 5.0, 8], float) # 하나의 데이터 타입만 취급 (다른 타입도 자동 변환)
test_array

array([1., 4., 5., 8.])

In [6]:
type(test_array[3])

numpy.float64

In [8]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]
a is b # is는 주소를 비교한다.

False

In [9]:
a[0] is b[-1] # 리스트는 -5 ~ 256 사이의 값에 대해 같은 정적 메모리 주소를 가리킨다

True

In [10]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1] 
# numpy ndarray는 정적 메모리를 사용하지 않기에 False 이다. (그냥 값을 진짜로 순차적으로 대입)

False

In [11]:
test_array.dtype # array의 전체 데이터 type를 반환
# 여기서는 float64이므로 64bit = 8byte 의 공간을 하나의 숫자가 점유한다.

dtype('float64')

In [14]:
a = np.array([[1,2,3],[4,5,6],[4,5,6]], float) #2차원 어레이를 보통 matrix라고 한다.
# 차후에 선형 대수를 배우면 rank라는 개념이 있는데, rank는 차원이 들어날 때 마다 하나씩 늘어난다.
a.shape # 튜플로 반환

(3, 3)

In [19]:
tensor = [
    [[1,2,5,6], [1,2,5,6], [1,2,5,6]],
    [[1,2,5,6], [1,2,5,6], [1,2,5,6]],
    [[1,2,5,6], [1,2,5,6], [1,2,5,6]]
]
new_tensor = (np.array(tensor))
new_tensor.shape

(3, 3, 4)

In [21]:
new_tensor.ndim # 차원을 반환

3

In [23]:
new_tensor.size # 데이터의 개수

36

In [24]:
np.array([[12,3,4],[4.5, '5', '6']], dtype=np.float32).nbytes # nbytes : 각 요소들의 바이트의 총합. (32[4byte] * 6 = 24byte)

24

## reshape

In [25]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [26]:
np.array(test_matrix).reshape(4,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [27]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [28]:
np.array(test_matrix).reshape(8)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [30]:
np.array(test_matrix).reshape(1,-1).shape # -1을 넣으면 나머지 값과 size를 고려하여 자동으로 값을 채운다.

(1, 8)

## flatten

In [32]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8])

In [33]:
np.array(test_matrix).flatten().shape

(8,)