## Numpy - operation function

- `sum`

In [17]:
import numpy as np

test_array = np.arange(1, 11).reshape(5, 2)
test_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
test_list = range(1, 11)
sum(test_list)  # list 와 동일

55

In [19]:
test_array.sum()  # 요소들의 값을 합산하여 반환 (실상 sum(list))와 동일

55

In [20]:
print(test_array.mean())  # 평균
print(test_array.var())  # 분산
print(test_array.std())  # 표준 편차

5.5
8.25
2.8722813232690143


In [24]:
test_array.sum(axis=0)  # 축을 지정하면 축마다 sum을 출럭 [1+3+5+7+9], [2+4+6+8+10]

array([25, 30])

In [25]:
test_array.sum(axis=1)  # 축을 지정하면 축마다 sum을 출럭 [1+2], [3+4], [5+6], [7+8], [9+10]

array([ 3,  7, 11, 15, 19])

In [29]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

In [32]:
third_order_tensor.sum(axis=2)  # [1+2], [3+4], [5+6], ... 각 층마다.

array([[ 3,  7, 11, 15, 19],
       [ 3,  7, 11, 15, 19],
       [ 3,  7, 11, 15, 19]])

In [33]:
third_order_tensor.sum(axis=1)  # [1+3+5+7+9] , [2+4+6+8+10]을 각 층마다 (즉, 각 3차원 층마다)

array([[25, 30],
       [25, 30],
       [25, 30]])

In [31]:
third_order_tensor.sum(axis=0)  # [1+1+1], [2+2+2], [3+3+3], ...

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24],
       [27, 30]])

In [34]:
test_array.mean(axis=1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [35]:
test_array.mean(axis=0)

array([5., 6.])

In [40]:
test_array.std(axis=1)

array([0.5, 0.5, 0.5, 0.5, 0.5])

### mathematical function

- `sqrt` : ndarray의 요소들의 제곱근 값을 반환 (return -> ndarray)  

In [38]:
np.sqrt(test_array)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974],
       [2.64575131, 2.82842712],
       [3.        , 3.16227766]])

In [41]:
np.exp(test_array)

array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04]])

### concatenate

In [43]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a, b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [47]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate((a, b), axis=1)

array([[1, 2, 3, 2, 3, 4]])

In [48]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])
np.concatenate((a, b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [105]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

# b.reshape(-1,2) # 차원 추가
print(b)

[5 6]


In [106]:
# 다른 방법의 차원 추가
b = b[np.newaxis, :]
print(b)  # b = [[5, 6]] 
print(b.T)


[[5 6]]
[[5]
 [6]]


In [107]:
np.concatenate((a, b.T), axis=1)  # concatenate는 행의 크기 (즉, 차원을 맞추어 주어야 한다.)

array([[1, 2, 5],
       [3, 4, 6]])

 - `.T` : 여기서의 `T`는 `ndarray` 의 property로 해당 `ndarray`의 전치 행렬을 return 합니다.

### Array operations
- dot product

In [108]:
# dot product
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(3, 2)

a.dot(b)

array([[ 58,  64],
       [139, 154]])

- transpose

In [109]:
# transpose

print(a.transpose())
a.T

[[1 4]
 [2 5]
 [3 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

### numpy performence

In [111]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result


iternation_max = 100000000
vector = list(range(iternation_max))
scalar = 2


# %timeit 을 통해 jupyter 환경에서 코드의 퍼포먼스를 확인할 수 있다.
%timeit sclar_vector_product(scalar, vector)  # for loop을 이용한 성능
%timeit [scalar * value for value in range(iternation_max)]  # list comprehension을 이용한 성능
%timeit np.arange(iternation_max) * scalar  # numpy를 이용한 성능

6.8 s ± 98.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7.11 s ± 77.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
205 ms ± 6.77 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


성능을 보았을 때 `numpy array` 가 가장 빠르다. (기본적으로 `list`는 -5 ~ 255까지는 정적으로 보관해서, 접근하려면, 2번에 걸쳐서 접근해야하므로 느림)
`numpy array`는 그냥 리스트를 일렬로 저장하는 구조이므로 접근이 빠름.

또한 `numpy` 는 `C`로 구현되어 있어 성능을 확보하는 대신, 파이썬의 가장 큰 특징인 dynamic typing을 포기함 (즉, `numpy array`는 하나의 데이터 타입만 대입 가능)
추가적으로 할당에 대해서는 속도 차이는 거의 없음.