# Numpy - create functions

## arange

In [4]:
import numpy as np

In [5]:
list(range(0, 10, 3))

[0, 3, 6, 9]

In [6]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
np.arange(0, 10, 0.5)  # float point로 step 변화 가능

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [8]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## ones, zeros & empty

In [9]:
np.zeros(shape=10, dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [10]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(10, dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [12]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.empty(10, np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [14]:
np.empty((10, 5))

array([[ 1.26659154e-311,  1.26659154e-311, -4.48068416e+027,
         1.26659154e-311,  1.26659154e-311],
       [-3.22742743e-102,  1.26659154e-311,  1.26659154e-311,
        -1.67411935e-147,  1.26659157e-311],
       [ 1.26659157e-311,  9.96366046e+092,  6.95271407e-310,
         6.95271407e-310, -1.08492981e-191],
       [ 1.26659154e-311,  1.26659154e-311, -1.98179865e-128,
         1.26659154e-311,  1.26659154e-311],
       [-2.13531619e+218,  1.26659154e-311,  1.26659154e-311,
        -8.51830503e+285,  1.26659154e-311],
       [ 1.26659154e-311,  3.54650022e-130,  1.26659167e-311,
         1.26659167e-311, -1.70009937e+232],
       [ 1.26659154e-311,  1.26659154e-311,  7.37072718e+160,
         1.26659139e-311,  1.26659139e-311],
       [ 8.97599387e+158,  1.26659151e-311,  1.26659151e-311,
         2.33014720e-113,  1.26659151e-311],
       [ 1.26659151e-311, -7.05461630e-293,  1.26659141e-311,
         1.26659141e-311, -1.25613091e-009],
       [ 1.26659150e-311,  1.26659150

In [15]:
test_mat = np.arange(100).reshape(5, -1)
test_mat.shape

(5, 20)

In [16]:
np.zeros_like(test_mat, np.int8)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int8)

## eye, identity & digonal

In [17]:
np.identity(10, np.int8)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [18]:
np.eye(3, 5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3, 5, k=2)  # k에 따라 시작 위치가 달라짐

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
mat = np.arange(12).reshape(3, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.diag(mat, k=2)  # 여기도 마찬가지로 k를 시작위치로 함

array([2, 7])

In [23]:
np.diag(mat, k=-1)  # 여기도 마찬가지로 k를 시작위치로 함

array([4, 9])

In [24]:
np.diag(mat, k=1)  # 여기도 마찬가지로 k를 시작위치로 함

array([ 1,  6, 11])

## random sampling - numpy.random

In [25]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.66662369, -0.10407089, -0.96868576,  1.41938676,  1.26890281],
       [ 1.43130287,  1.0322257 , -0.63250276,  0.05837004,  0.06369679]])

In [26]:
np.random.exponential(scale=2, size=100)

array([ 0.30223268,  0.88059294,  1.69118907,  0.80634743,  3.70579547,
        3.32752553,  1.07795733,  0.97452195,  0.28657193,  0.75711314,
        1.58936115,  3.41476534,  1.11593123,  0.0907624 ,  3.46948353,
        0.07342475,  1.71155604,  0.68820009,  0.28827209,  1.94079998,
        0.22070923,  0.06835269,  1.25449255,  0.24614436,  1.69281295,
        2.04803619,  1.73000303,  1.07948613,  0.2580473 ,  0.01599463,
        0.87973765,  0.61335294,  0.73350945,  0.74483273,  3.27589246,
        0.2544808 ,  0.88361176,  5.02875955,  4.36074811,  0.44563763,
        1.14836321,  1.57771446,  2.47362839,  0.18479927,  3.92708184,
        0.88787093,  0.68766986,  0.43648796,  1.52190319,  0.15850586,
        0.7060899 ,  0.01310421,  1.96819412,  0.58950656,  0.63233719,
        4.3350927 ,  0.29531273,  1.66054907,  2.8177082 ,  2.12219558,
        0.46946199,  0.28040274,  0.94302422,  4.01884045,  1.19403058,
        0.62669131,  1.25039771,  1.76850212,  0.98100973,  1.38