## Numpy comparsions

In [14]:
import numpy as np

In [15]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

부등호도 broadcasting 되어서 각각의 요소마다 비교되어 값이 출력된다고 보면 된다. (결과는 `boolean array` 가 나온다고 한다.)

In [16]:
a < 4

array([ True,  True,  True, False, False, False, False, False, False])

In [17]:
a < 1

array([False, False, False, False, False, False, False, False, False])

### all & any

`all` 은 `and` 연산자의 역할로 모든 `array` 상의 데이터가 `True` 일 때만 `True`
`any` 은 `or` 연산자의 역할로 어느 한 데이터의 `array` 상의 데이터만 이라도 `True` 이면 `True`

In [18]:
np.any(a)

True

In [19]:
np.all(a)  # 그냥 쓰면 0이 아닌 값이 없으면 True

True

In [20]:
np.any(a < 4)

True

In [21]:
np.all(a < 4)

False

### comparison operation

In [45]:
a = np.array([2, 3, 0])

np.logical_and(a > 0, a < 3)  # a > 0 : [T,T,T], a < 3 : [T,F,T] --> logical_and : [T,F,T]   

array([ True, False, False])

### np.where

In [46]:
a

array([2, 3, 0])

In [47]:
np.where(a > 1, 1, 0)  # np.where(condition, true, false)

array([1, 1, 0])

In [48]:
np.where(a > 1)  # True index만 return --> 결과가 튜플

(array([0, 1], dtype=int64),)

In [49]:
np.where(a > 1)[0]

array([0, 1], dtype=int64)

In [42]:
a = np.array([1, np.NaN, np.inf])  # np.NaN : not a number, np.inf : infinite (수렴 X)
np.isnan(a)  # isnan : not a number인지 출력

array([False,  True, False])

In [43]:
np.isfinite(a)  # finite num에 대해서 true

array([ True, False, False])

### argmax & argmin

In [50]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [51]:
a.argsort()  # array의 요소들을 sorting하여 그 인덱스를 순서대로 보임.

array([0, 1, 7, 2, 3, 4, 6, 5], dtype=int64)

In [52]:
a.argsort()[::-1]  # array의 요소들을 sorting하여 그 인덱스를 역순으로 보임.

array([5, 6, 4, 3, 2, 7, 1, 0], dtype=int64)

In [53]:
np.argmax(a)  # 최대 값을 갖는 요소의 index를 보임

5

In [54]:
np.argmin(a) # 최소 값을 갖는 요소의 index를 보임

0

In [55]:
a = np.array([[1,2,4,7], [9,88,7,6],[12,34,5,7]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  7,  6],
       [12, 34,  5,  7]])

In [56]:
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 0, 1], dtype=int64))