### Array operations
- dot product

In [1]:
import numpy as np

In [2]:
# dot product
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(3, 2)

a.dot(b)

array([[ 58,  64],
       [139, 154]])

- transpose

In [3]:
# transpose

print(a.transpose())
a.T

[[1 4]
 [2 5]
 [3 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

### numpy performence

In [4]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result


iternation_max = 100000000
vector = list(range(iternation_max))
scalar = 2


# %timeit 을 통해 jupyter 환경에서 코드의 퍼포먼스를 확인할 수 있다.
%timeit sclar_vector_product(scalar, vector)  # for loop을 이용한 성능
%timeit [scalar * value for value in range(iternation_max)]  # list comprehension을 이용한 성능
%timeit np.arange(iternation_max) * scalar  # numpy를 이용한 성능

6.67 s ± 58.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


KeyboardInterrupt: 

성능을 보았을 때 `numpy array` 가 가장 빠르다. (기본적으로 `list`는 -5 ~ 255까지는 정적으로 보관해서, 접근하려면, 2번에 걸쳐서 접근해야하므로 느림)
`numpy array`는 그냥 리스트를 일렬로 저장하는 구조이므로 접근이 빠름.

또한 `numpy` 는 `C`로 구현되어 있어 성능을 확보하는 대신, 파이썬의 가장 큰 특징인 dynamic typing을 포기함 (즉, `numpy array`는 하나의 데이터 타입만 대입 가능)
추가적으로 할당에 대해서는 속도 차이는 거의 없음.