# Numpy - boolean & fancy index

In [1]:
import numpy as np

### boolean index

In [2]:
arr = np.array([1,4,0,2,3,9,8,7], dtype=float)
arr[arr > 5] # boolean index에 따라 조건에 맞는 요소들로만 array 구성

array([9., 8., 7.])

**boolean index**를 수행하려면, `arr`과 `boolean index`의 **크기(shape)** 가 당연히 동일해야 함. 
(아니면 모든 요소 탐색 불가)

### fancy index

In [5]:
a = np.array([2,4,6,8])
cond = np.array([1,1,1,2,1,3,0])

In [6]:
a.take(cond) # takc 함수 : bracket index와 같은 효과

array([4, 4, 4, 6, 4, 8, 2])

In [7]:
a[cond]

array([4, 4, 4, 6, 4, 8, 2])

In [8]:
a = np.array([[1,4],[6,16]])
b= np.array([0,0,1,1,0])
c= np.array([0,1,1,1,1])

a[b, c] # matrix 형태의 fancy indexing

array([ 1,  4, 16, 16,  4])

In [9]:
a[b] #2차원 어레이의 row index의 형태로 return

array([[ 1,  4],
       [ 1,  4],
       [ 6, 16],
       [ 6, 16],
       [ 1,  4]])