## Numpy - operation function

- `sum`

In [17]:
import numpy as np

test_array = np.arange(1, 11).reshape(5, 2)
test_array

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
test_list = range(1, 11)
sum(test_list)  # list 와 동일

55

In [19]:
test_array.sum()  # 요소들의 값을 합산하여 반환 (실상 sum(list))와 동일

55

In [20]:
print(test_array.mean())  # 평균
print(test_array.var())  # 분산
print(test_array.std())  # 표준 편차

5.5
8.25
2.8722813232690143


In [24]:
test_array.sum(axis=0)  # 축을 지정하면 축마다 sum을 출럭 [1+3+5+7+9], [2+4+6+8+10]

array([25, 30])

In [25]:
test_array.sum(axis=1)  # 축을 지정하면 축마다 sum을 출럭 [1+2], [3+4], [5+6], [7+8], [9+10]

array([ 3,  7, 11, 15, 19])

In [29]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]]])

In [32]:
third_order_tensor.sum(axis=2)  # [1+2], [3+4], [5+6], ... 각 층마다.

array([[ 3,  7, 11, 15, 19],
       [ 3,  7, 11, 15, 19],
       [ 3,  7, 11, 15, 19]])

In [33]:
third_order_tensor.sum(axis=1)  # [1+3+5+7+9] , [2+4+6+8+10]을 각 층마다 (즉, 각 3차원 층마다)

array([[25, 30],
       [25, 30],
       [25, 30]])

In [31]:
third_order_tensor.sum(axis=0)  # [1+1+1], [2+2+2], [3+3+3], ...

array([[ 3,  6],
       [ 9, 12],
       [15, 18],
       [21, 24],
       [27, 30]])

In [34]:
test_array.mean(axis=1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [35]:
test_array.mean(axis=0)

array([5., 6.])

In [40]:
test_array.std(axis=1)

array([0.5, 0.5, 0.5, 0.5, 0.5])

### mathematical function

- `sqrt` : ndarray의 요소들의 제곱근 값을 반환 (return -> ndarray)  

In [38]:
np.sqrt(test_array)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974],
       [2.64575131, 2.82842712],
       [3.        , 3.16227766]])

In [41]:
np.exp(test_array)

array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04]])

### concatenate

In [43]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a, b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [47]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate((a, b), axis=1)

array([[1, 2, 3, 2, 3, 4]])

In [48]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])
np.concatenate((a, b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [105]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

# b.reshape(-1,2) # 차원 추가
print(b)

[5 6]


In [106]:
# 다른 방법의 차원 추가
b = b[np.newaxis, :]
print(b)  # b = [[5, 6]] 
print(b.T)


[[5 6]]
[[5]
 [6]]


In [107]:
np.concatenate((a, b.T), axis=1)  # concatenate는 행의 크기 (즉, 차원을 맞추어 주어야 한다.)

array([[1, 2, 5],
       [3, 4, 6]])

 - `.T` : 여기서의 `T`는 `ndarray` 의 property로 해당 `ndarray`의 전치 행렬을 return 합니다.